FROM python:3.7-alpine

COPY ./requirements.txt /src/requirements.txt
WORKDIR /src/

RUN pip install -r /src/requirements.txt

COPY ./src/server /src/server
COPY ./src/main.py /src/main.py
COPY ./server.yaml /server.yaml


CMD ["python", "main.py", "c"]